### ISSUE TITLE
Make PathfinderBegin and PathfinderRun automatic

### ISSUE THREAD

**Issue by aryabhatta-dey** [AlphaMycelium/pathfinder.vim#12]
This is a feature request to make the plugin track my position between edits and take those two points as the beginning and ending points for the path to be optimized. The way this can work is PathfinderBegin is auto set to take the point where the last edit was made as the starting pint and the moment I do an edit PathfinderRun auto runs.

**Comment by AlphaMycelium** [comment]
## Possible implementation

This could be done by starting a background thread in Python, and sending it `CursorMoved` events using an autocmd.

> **CursorMoved**  -  After the cursor was moved in Normal mode. Also when the text of the cursor line has been changed, e.g., with "x", "rx" or "p". Not triggered when there is typeahead or when an operator is pending. For an example see |match-parens|.

When the thread receives no motions for a while (`g:pf_autorun_delay`?), it will generate a path between the position the cursor was at before and after. `x`,`rx`,`p` and so on should finish the movement regardless of the delay, as well as leaving normal mode.

Running on a thread means Vim is not blocked, so the user can continue working while the path is processed. Once pathfinding completes, the result should be shown only if it is shorter than the recorded input. For example, you don't want `gg` appearing as a suggestion if you used `2k` to get to the same place.

I suggest using a [popup window](https://vimhelp.org/popup.txt.html) either next to the cursor or in a corner of the screen to show suggestions in a notification style. If the current vim doesn't have `+popupwin`, then just echo it.

This behaviour should be able to be disabled, e.g. by setting the delay option to a negative value. In that case, the current commands would still be available to use manually.

**Comment by AlphaMycelium** [comment]
#11 would only be useable with manual commands since it'd take up a lot of screen space appearing all the time.

**Comment by AlphaMycelium** [comment]
The path should finish on:
- No `CursorMoved` events received for `g:pf_autorun_delay`
- `CursorMoved` caused the current line to be modified
- `InsertEnter`
- `WinLeave`

**Comment by AlphaMycelium** [comment]
@aryabhatta-dey I have just realised that running the pathfinder in a thread would still cause the cursor to jump around while motions are tested. Don't know why I didn't think of that before.

I've had an idea how to work around this:

1. When Vim is opened, launch another instance of Vim in a subprocess (`subprocess.Popen`), with `-u` set to a custom vimrc included with the plugin. (If one of these is already running, don't start another, so it is shared between all Vims the user has open.)
2. The custom vimrc loads the pathfinding code and starts a `multiprocessing.connection.Listener` or similar to listen for pathfinding requests.
3. When a path needs to be calculated:
  1. Save a temporary session file containing the current windows, buffers and other necessary information.
  2. Tell sub-Vim to load that session file.
  3. Send the start and target positions. Pathfinding runs in the background instance of Vim, while the user continues to work.
  4. Sub-Vim sends the finished path back to the client.
  5. Client (the main Vim) displays the received path.
4. Ensure that the subprocess Vim closes itself when all other Vim instances are closed.

Alternatively, we could re-implement all the supported motions in Python to operate on a string version of the buffer, but that seems like a ton of work.
