### ISSUE TITLE
Can I configure how long the suggestions appear?

### ISSUE THREAD

**Issue by coaxial** [AlphaMycelium/pathfinder.vim#35]
I find that the amount of time the popup is shown is a bit too short for me to read and assimilate.

Is there a setting in the plugin to make the duration the popup is shown a bit longer?

**Comment by AlphaMycelium** [comment]
Not yet, although it shouldn't be difficult to add one.

**Comment by AlphaMycelium** [comment]
Okay, you should be able to change `g:pf_popup_time`, which is in milliseconds. (default 3000)

**Comment by coaxial** [comment]
Thank you
