### ISSUE TITLE
Set fg/bg color of popup

### ISSUE THREAD

**Issue by hejops** [AlphaMycelium/pathfinder.vim#43]
On certain colorschemes (e.g. koehler, among others), popups appear un-highlighted. This can make it difficult to distinguish popups from actual text.

![Screenshot_2020-07-02_17-52-52](https://user-images.githubusercontent.com/11556924/86381405-971ea500-bc8d-11ea-8d01-b22ef28c7b9a.png)

Is there a way to configure the appearance of the popup?

**Comment by AlphaMycelium** [comment]
Currently it uses the `Cursor` highlight group. There used to be a separate group called `PathfinderPopup` but that was [removed in v2](https://github.com/AlphaMycelium/pathfinder.vim/releases/tag/v2.0.0). I think it should be possible to add it back in and inherit from `Cursor` if it's not set.
